plugins:
  ginbits:
    plugins:
    - approve
    - assign
    - blunderbuss
    - cat
    - cla
    - config-updater
    - dog
    - golint
    - goose
    - heart
    - help
    - hold
    - invalidcommitmsg
    - label
    - lgtm
    - lifecycle
    - milestoneapplier
    - override
    - owners-label
    - pony
    - retitle
    - shrug
    - sigmention
    - size
    - skip
    - slackevents
    - transfer-issue
    - trick-or-treat
    - trigger
    - verify-owners
    - welcome
    - wip
    - yuks
external_plugins:
  ginbits:
  - name: needs-rebase
    events:
      - issue_comment
      - pull_request
  - endpoint: http://cherrypicker
    events:
    - issue_comment
    - pull_request
    name: cherrypicker
config_updater:
  maps:
    config/jobs/**/**/*-master-periodics.yaml:
      namespace: ci
      name: job-config
    config/jobs/**/**/*-master-postsubmits.yaml:
      namespace: ci
      name: job-config
    config/jobs/**/**/*-master-presubmits.yaml:
      namespace: ci
      name: job-config
    config/jobs/**/**/*-staging-periodics.yaml:
      namespace: ci
      name: job-config
    config/jobs/**/**/*-staging-postsubmits.yaml:
      namespace: ci
      name: job-config
    config/jobs/**/**/*-staging-presubmits.yaml:
      namespace: ci
      name: job-config
    config/jobs/**/**/*-development-periodics.yaml:
      namespace: ci
      name: job-config
    config/jobs/**/**/*-development-postsubmits.yaml:
      namespace: ci
      name: job-config
    config/jobs/**/**/*-development-presubmits.yaml:
      namespace: ci
      name: job-config
    cluster/prow/config/config.yaml:
      namespace: ci
      name: config
    cluster/prow/config/plugins.yaml:
      namespace: ci
      name: plugins
    cluster/commitlint/commitlint.config.js:
      namespace: ci
      name: commitlint-config
